config/routes.rb
Rails.application.routes.draw do
  get 'monumentdistance/new'

  get 'scots/new'

  get 'teams/new'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'monuments' => 'static_pages#monuments'
  get 'monumentsmap' => 'static_pages#monumentsmap'
  get 'monumentsgraph' => 'static_pages#monumentsgraph'
  get 'results' => 'static_pages#results'
  get 'one'     => 'static_pages#one'
  get 'two'     => 'static_pages#two'
  get 'three'     => 'static_pages#three'
  get 'four'     => 'static_pages#four'
  get 'five'     => 'static_pages#five'
  get 'six'     => 'static_pages#six'
  get 'seven'     => 'static_pages#seven'
  get 'eight'     => 'static_pages#eight'
  get 'nine'     => 'static_pages#nine'
  get 'ten'     => 'static_pages#ten'
  get 'eleven'     => 'static_pages#eleven'
  get 'twelve'     => 'static_pages#twelve'
  get 'thirteen'     => 'static_pages#thirteen'
  get 'fourteen'     => 'static_pages#fourteen'
  get 'fifteen'     => 'static_pages#fifteen'
  get 'sixteen'     => 'static_pages#sixteen'
  get 'seventeen'     => 'static_pages#seventeen'
  get 'eighteen'     => 'static_pages#eighteen'
  get 'nineteen'     => 'static_pages#nineteen'
    get 'twenty'     => 'static_pages#twenty'
  get 'twentyone'     => 'static_pages#twentyone'
    get 'twentytwo'     => 'static_pages#twentytwo'
      get 'twentythree'     => 'static_pages#twentythree'
        get 'twentyfour'     => 'static_pages#twentyfour'
          get 'twentyfive'     => 'static_pages#twentyfive'
            get 'twentysix'     => 'static_pages#twentysix'
              get 'twentyseven'     => 'static_pages#twentyseven'
                get 'twentyeight'     => 'static_pages#twentyeight'
                  get 'twentynine'     => 'static_pages#twentynine'
                    get 'thirty'     => 'static_pages#thirtyone'
                      get 'thirtyone'     => 'static_pages#thirtyone'
                       get 'thirtytwo'     => 'static_pages#thirtytwo'

  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  get 'summonersearch' => 'static_pages#summonersearch'
  post 'login'  => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-fixed-top">
      <div class= "header">

         Calderdale's Ancient Monuments 

      </div>     

<!-- Navagation Bar -->
        <nav class="navbar navbar-default">
          <div class="headcontainer-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
              </button>
              
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
              <ul class="nav navbar-nav">
              
             
                   <li><%= link_to "Home", root_path, class: "btn btn-primary" %></li><br>
        <li><%= link_to "Monuments", monuments_path, class: "btn btn-primary" %></li><br>
        <li><%= link_to "Monuments Map", monumentsmap_path, class: "btn btn-primary", 'data-no-turbolink' => true  %></li><br>
        <li><%= link_to "Monuments Graph", monumentsgraph_path, class: "btn btn-primary", 'data-no-turbolink' => true  %></li><br>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path, class: "btn btn-primary" %></li>
          <li class="dropdown">
            <a href="#" class="btn btn-default dropdown-toggle", data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user, class: "btn btn-primary" %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: "btn btn-primary" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Logout", logout_path, method: "delete", class: "btn btn-primary" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path, class: "btn btn-primary" %></li>
          


          
          
        <% end %>
            
              </ul>
            </div>
          </div>
        </nav>
  </nav>






</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- chartkick shit -->
      <%= stylesheet_link_tag    'application', media: 'all' %>
      <%= javascript_include_tag "//www.google.com/jsapi" %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'http://yandex.st/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'http://yandex.st/bootstrap/3.1.1/js/bootstrap.min.js' %>
  
  <%= csrf_meta_tags %>
  <style>

</style>
  </head>
<body>

  
  <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      

      <%= yield %>
      
    
</div>
<!-- chartkick shit -->
  <div class="container">
    <%= yield %>
  </div>
<!-- -->

<%= render 'layouts/footer' %>
</body>

    

       <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %> 
      
      
</html>